// <auto-generated />
namespace ObligatorioP3MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class required_telefono_organizador : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required_telefono_organizador));
        
        string IMigrationMetadata.Id
        {
            get { return "201711260439342_required_telefono_organizador"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
